### ISSUE TITLE
config.example.py missing

### ISSUE THREAD

**Issue by jartigag** [TLMn00bs/AoC-Bot#4]
pos eso, que falta un `config.example.py` :innocent:

lo puede añadir cualquiera de los que conozcáis como funciona esto porque hayáis trasteado con el bot

**Comment by lassa97** [comment]
Solved in  commit #f3671e160e98f3f5dde01ea877281d67a016281f and #c8626c4e70f7e603fbc7c62ec34e49bda7c22094

**Comment by lassault** [comment]
Solved in commit #f3671e160e98f3f5dde01ea877281d67a016281f and #c8626c4e70f7e603fbc7c62ec34e49bda7c22094
